name: Release Extension

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # or another version if you prefer

    - name: Install dependencies
      run: npm install

    - name: Package VSCode Extension
      run: npx vsce package -o metaconfig-extension.vsix

    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v2
      with:
        name: vscode-extension
        path: ./*.vsix

